secret_token: "[SECRET TOKEN GOES HERE]"
sign: '!'
max_msg_length: 2000
dir:
  localization:
    - data
    - localizations
    - commands_EN.yaml
database:
  active: False
identity:
  identity_dir:
    - data
    - identity_files
  default_identity: default_EN.yaml
  identity_files:
    - project_gm.yaml
  default_verbose: False
  default_interval: 0
  universal_phrases: []
  default_difficulty: 3
  difficulty_table:
    simple: 1
    easy: 2
    normal: 3
    hard: 4
    expert: 5
birthdays:
  channels: ["main", "general"]
commands:
  nicknames: False
  echo: False
  poll: False
  calendar: False
  character_list: False
  dice: False
  god_dice: False
  cheat_dice: False
  remindme: False
  tic-tac-toe: False
  minesweeper: False
  wheel: False