secret_token: "[SECRET TOKEN GOES HERE]"
sign: '!'
max_msg_length: 2000
dir:
  localization:
    - data
    - localizations
    - commands_EN.yaml
database:
  active: True
  ini_file:
    - database
    - database.ini
  db_section: 'postgresql'
identity:
  identity_dir:
    - data
    - identity_files
  default_identity: default_EN.yaml
  identity_files:
    - project_gm.yaml
    - butler.yaml
    - robot.yaml
  facts_file: general_facts.yaml
  universal_phrases:
    morning: "(goe(d|i)emorgen|mogg(e|u))"
    night: "(\\b(wel)?te?rusten?\\b|slaap lekker|good night)"
    thanks: "((bedankt|thank you|thanks|dank ?je ?(wel)?),? {})"
  default_difficulty: 3
  difficulty_table:
    simple: 1
    easy: 2
    normal: 3
    hard: 4
    expert: 5
calendar:
  active: True
  max_event_name: 25
  max_event_description: 255
  date_format: "%a %d %B, %Y"
  time_format: "%H:%M"
  default_shadow: 3
  max_shadows: 9
  synonyms:
    mention: "tag"
    title: "name"
    time: "date"
    reminders: "reminder"
character_list:
  active: True
  list_dir:
    - data
    - character_lists
  lists:
    - "setting_name"
  setting_name:
    file: "empty_list.xml"
    owner: 000000000000000001
    default_year: 1999
    color: f0f0f0
dice:
  active: True
  god_module: True
  cheat_module: True
  dice_softcap:  20
  dice_hardcap: 100
  dice_max_sides: 1000
nicknames:
  max_length: 40
  default_nicknames:
    - "The Void"
    - "Ishmael"
    - "maybe"
    - "Spartacus"
tic-tac-toe:
  active: True
  pieces: [":x:", ":o:"]
  empty: ":white_large_square:"
  canton: ":black_large_square:"
  rows: [":one:", ":two:", ":three:"]
  columns: [":regional_indicator_a:", ":regional_indicator_b:", ":regional_indicator_c:"]
minesweeper:
  active: True
  max_size: 199
  AI_table:
    1: [6, 4]
    2: [8, 6]
    3: [12, 8]
    4: [14, 10]
    5: [17, 11]
  AI_bombs:
    1: 1
    2: 5
    3: 14
    4: 25
    5: 38
wheel:
  active: True
  words_file:
    - data
    - wheel
    - word_list.yaml
  display:
    letter: ":regional_indicator_{}:"
    hidden: ":white_large_square:"
    space: ":black_large_square:"
    punctuation: {",": ":arrow_heading_down:", "-": ":no_entry:", "_": ":no_entry:"}
  wheel_layout: [BANKRUPT, 90, 50, 65, 50, 80, LOSETURN, 70, FREESPIN, 65, BANKRUPT, 60,
                 50, 55, 60, 100, 70, 50, 65, 60, 70, 60, 50, 250]
  freespin_value: 50
  vowel_cost: 25
